version: "2"
services:
 main: 
  build: .
  ports:
   - "80:3000"
  links:
   - mongodb
  environment:
   MONGO_URL: mongodb://mongodb
   STARTUP_DELAY: 10
 mongodb:
  image: mongo
  volumes:
   - ./data/mongo:/data/db
