version: "2"
services:
 main: 
  image: viziquer/viziquer
  ports:
   - "80:3000"
  links:
   - mongodb
  environment:
   MONGO_URL: mongodb://mongodb/vq
   STARTUP_DELAY: 10
 mongodb:
  image: mongo
  volumes:
   - ./data/mongo:/data/db

