env:
  browser: true
  es2021: true
  node: true
  meteor: true
  jest: true
extends: 
  # - airbnb-base
  - eslint:recommended
  # - plugin:meteor/recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver: meteor
plugins:
  - meteor
rules:
  # no-undef: 0
  # no-redeclare: 0
  # no-unreachable: 0
  no-unused-vars: 0
  no-empty: 0
  no-useless-escape: 0
  no-extra-semi: 0
  no-mixed-spaces-and-tabs: 0
globals:
  Meteor: false
  Npm: false
  Session: false
  Template: false
  BlazeLayout: false
  ReactiveVar: false
  $: false
  _: false
  Konva: false
  YASQE: false
  Restivus: false
  xml2js: false
  IMCSLayout: false
  TAPi18n: false
  pdfMake: false
